### PR TITLE
support Reconyx makernote

### PR DESCRIPTION
**Pull request by twest820**
Moving ahead with a pull request for lack of response on metadata-extractor-dev.  Changes here should be OK on the basics but some style adjustment and trimming the .jpg into a binary fragment may be desirable.  Please advise.  I looked round a bit for guidance on the trimming process and how to get the right part of the file but didn't spot any.

### CODE REVIEW

**Comment by drewnoakes** [comment]
Todd, apologies for dropping the email chain. I'm looking after a one year old this week on my own and not getting much else done. He's just gone to sleep, so this comes at a good moment.

It looks good, nice one. Only nit is the indentation and formatting changes to `ExifTiffHandler.cs`.

As you mention, there are many ways of handling test data to validate the correctness of your metadata processor. I've put some thoughts about this on to the wiki here:

https://github.com/drewnoakes/metadata-extractor/wiki/Working-with-test-images

In this case the file is a non-trivial 344 KB, and I don't think there's any value having those unit tests if you use the `metadata-extractor-images` repo (correct me if I'm wrong). You could extract the bytes, but it's a more thorough test to track diffs to a versioned and verbose log of details regarding the file.

**Comment by twest820** [comment]
Hey Drew, that’s no problem.  Thanks for the wiki!  I can add images from a couple Fujifilm X bodies to metadata-extractor-images as well as a few Bushnell trail cameras too.  Got a full day in the field tomorrow, so probably Friday for getting the pull requests updated.

 

Sorry about the ExifTiffHandler formatting changes.  I had ignore whitespace on in SourceTree and didn’t even notice, easy reverts.

 

Todd

**Comment by drewnoakes** [comment]
That's great, thanks! It'll take a while to clone the images repo so kick
that off early if you can. I should update the wiki to explain how to
process all the images and update the metadata logs. For .NET it's one of
the projects in the code, though iirc you may have to toggle some comments
in Program.cs.

[via phone]

On 8 Sep 2016 04:26, "Todd West" <notifications@github.com> wrote:

Hey Drew, that’s no problem. Thanks for the wiki! I can add images from a
couple Fujifilm X bodies to metadata-extractor-images as well as a few
Bushnell trail cameras too. Got a full day in the field tomorrow, so
probably Friday for getting the pull requests updated.



Sorry about the ExifTiffHandler formatting changes. I had ignore whitespace
on in SourceTree and didn’t even notice, easy reverts.



Todd

**Comment by drewnoakes** [comment]
I added some more info to the wiki page:

https://github.com/drewnoakes/metadata-extractor/wiki/Working-with-test-images#running-regression-tests

**Comment by twest820** [comment]
Thanks, I'd found MetadataExtractor.FileProcessor.exe and figured as much. From the .gitattributes it looks like trouble with getting meaningless diffs for every metadata\.txt in git because of newline differences is known. FWIW I still hit the problem (Win10, git 2.8.1, SourceTree 1.9.6.1, core.autocrlf true) and am just going to ignore it after looking through a reasonable sampling of files spuriously flagged as different.

**Comment by twest820** [comment]
Changes pushed, checks passed.

**Comment by drewnoakes** [comment]
Great stuff.

**Comment by twest820** [comment]
Thanks for the merges!  One follow up question: is there a timeframe when v1.5 might be expected on nugget.org?

**Comment by drewnoakes** [comment]
I'll take a look now.

**Comment by drewnoakes** [comment]
1.5.0 is on NuGet. Would be great if you could try it out and let me know if you're having any trouble.

**Comment by twest820** [comment]
Sweet!  Looks ok from [an initial acceptance test](https://github.com/CascadesCarnivoreProject/Timelapse/commit/266ae4449839e63d9e87c014c862e2aa7b4f5fca).  We'll get more cooked over the next few weeks.  (I am still trying to get a response from Reconyx on their makernote specification, too.)

**Comment by drewnoakes** [comment]
Nice project. I added a link to it here:

https://github.com/drewnoakes/metadata-extractor-dotnet/wiki/Used-By

**Pull request merged**
