### PR TITLE
Add string timezone tags

### PR DESCRIPTION
**Pull request by dmitry-shechtman**

### CODE REVIEW

**Comment by drewnoakes** [comment]
I'll run this over the image library to see how many hits we get.

**Comment by drewnoakes** [comment]
They came up in images from a Sony camera.

**Comment by dmitry-shechtman** [comment]
I encountered these in CR3 images, so newer Canon models seem to produce them as well.

**Comment by drewnoakes** [comment]
> I encountered these in CR3 images

Can you contribute a sample image? The actual image isn't important.

**Comment by dmitry-shechtman** [comment]
All the images I tested on are from https://github.com/lclevy/canon_cr3

**Comment by drewnoakes** [comment]
Thanks, I've reached out to the author of those images. Hopefully they get back to me and give us permission to add them to the image library.

**Pull request merged**
