### PR TITLE
Added quick time metadata with no default locale.

### PR DESCRIPTION
**Pull request by kastwey**
Removed the limitation of only default locale is supported. Now, all fields are retrieved, but without locale tag. This should be supported in future. For now, at least, we have the description metadata, which is useful for blind people, I.E., in Apple iPhone, when users labeled the pictures with Voice Over.

### CODE REVIEW

**Comment by drewnoakes** [comment]
@kastwey thanks very much for your contributions. Are you able to provide a sample file that reproduces this problem?

**Comment by kastwey** [comment]
Hi,

Yes, I have a video with this description in quick time directory.

[11. Kastwey kicking a dead man and giving the command to amaterasu_n.zip](https://github.com/drewnoakes/metadata-extractor-dotnet/files/4937284/11.Kastwey.kicking.a.dead.man.and.giving.the.command.to.amaterasu_n.zip)

Thanks!

**Comment by drewnoakes** [comment]
Thanks very much for the PR and the sample file.

**Comment by kastwey** [comment]
Thanks!

**Pull request merged**
