### PR TITLE
Hold xmp array and lazy-load XmpMeta in XmpDirectory

### LINKED ISSUE #109: Unsupported Encoding attempting to read XMP data from Ricoh Theta S image
Hi,

As recommended in https://stackoverflow.com/questions/46610818/unsupported-encoding-error-in-xmp-directory  Here's an attached image that is giving me an Unsupported Encoding error in the Xmp Directory.  I do not actually get a stack trace, just and error in the _errorsList.

The issue is perhaps in XmpCore? I walked through metadata extractor with my debugger and reached a point where it hands off the file to XmpCore to parse and that call returns the error.

Here's a sample image :
r0010025

### PR DESCRIPTION
**Pull request by kwhopper**
Replace null characters (0x00) with a space (0x20) to make XML array acceptable to XDocument/XmlReader in XmpCore.

This commit should fix #109 and #134 

(Note that the IsLegalXmlCharacter function could check across the entire range of valid characters. Decided to start out conservatively)

### CODE REVIEW

**Comment by kwhopper** [comment]
I reverted this but kept the changes as a comment.

Instead, this holds the XMP byte array in the XmpDirectory and lazy loads an XmpMeta object on request. If there are failures, this gives the consumer access to the original byte array through TagXmpByteArray

**Comment by kwhopper** [comment]
This was reverted and modified because I saw a number of embedded XMP's that weren't fixed by replacing with spaces. It seems better in the long run to hold the bytes instead and (maybe) provide some sanitation methods for common problems. I don't think we'll ever be able to handle all cases of bad embedded XMP.

**Comment by drewnoakes** [comment]
@kwhopper firstly let me apologise for leaving your PRs so long without any kind of feedback. I started a new role a few weeks back and life before and after that was uncommonly busy. I should have a little more time to devote to the project over the next while.

It's hard to say without looking closely at the bytes and the encodings we're using with them. `\0` is perfectly valid in many encodings, so we can't simply replace them in the byte stream. If there's a single encoding, there are probably some simple rules that can be used for sanitisation. However, most strings of data seen by MetadataExtractor can be expected to have every encoding under the sun...

My concern with retaining arbitrary-length `byte[]`s in memory is that if images contain over 85kB of XMP (not inconceivable) then their `byte[]` must be allocated on the LOH. In workloads that involve processing large numbers of images, the LOH can struggle under such high levels of pressure.

It's been a while since I looked at the project so let me spend some time to get my thoughts together about all the bits we have at the moment and put together a plan.

**Comment by kwhopper** [comment]
This might have potential:
https://www.nuget.org/packages/System.Buffers

**Pull request closed without merging**
