### PR TITLE
WIP configuring docfx to generate API documentation.

### PR DESCRIPTION
**Pull request by markegorman**
I hope y'all not mad

### CODE REVIEW

**Comment by drewnoakes** [comment]
Hey Mark. No worries, take your time. It's ok being new to GitHub.

What are you trying to do? Perhaps we can lend a hand.

**Comment by markegorman** [comment]
Upload files from a phone it a pain and I’m sry for a pain if there is anything I can do please let me know
Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by markegorman** [comment]
base

**Comment by drewnoakes** [comment]
What files are you trying to upload?

**Pull request closed without merging**
